Aim 2: Notebook
===================




## Coding Notebook

```{r include = FALSE}
knitr::read_chunk("./helpers.R")
if (interactive()) source("./helpers.R")
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r helpers, message = FALSE, warning = FALSE}
```

```{r, include = FALSE}
library(rstanarm)
theme_set(theme_grey())
knitr::opts_chunk$set(cache = TRUE)
```

```{r}
d <- readr::read_csv("./data/aim2-model-ready.csv.gz") %>% 
  filter(!is.na(Bias_Fam)) %>% 
  filter(300 <= Time) %>% 
  select(-starts_with("ot")) %>% 
  polypoly::poly_add_columns(
    Time, degree = 3, scale_width = 1, prefix = "ot")

ggplot(d) + 
  aes(x = Time, y = Prop, color = Bias_Fam) + 
  facet_wrap(Condition ~ Study) + 
  geom_line(aes(group = interaction(ResearchID, Bias_Fam)), alpha = .1) +
  guides(color = FALSE) + 
  scale_color_viridis_d(end = .8) + 
  stat_smooth(method = "gam", formula = y ~ s(x), se = FALSE)

summary(d)
```



```{r}

d_r_ui <- d %>% 
  filter(Condition == "real", Bias_Fam == "Unfamiliar") %>% 
  mutate(elog = empirical_logit(Target, Distractor))


d_bias_target <- tibble::tribble(
  ~Condition, ~Bias_Fam, ~Bias_Target,
  "nonsense", "Familiar", "Distractor",
  "nonsense", "Unfamiliar", "Target",
  "real", "Familiar", "Target",
  "real", "Unfamiliar", "Distractor")

d_r_nw_vs <- d %>% 
  select(-Primary, -.response_def, -Prop, -PropSE) %>% 
  filter(Condition != "MP") %>% 
  rename(Unfamiliar = Distractor, Familiar = Target) %>% 
  mutate(
    Target = ifelse(Condition == "nonsense", Unfamiliar, Familiar), 
    Distractor = ifelse(Condition == "nonsense", Familiar, Unfamiliar)) %>% 
  left_join(d_bias_target) %>% 
  mutate(elog = empirical_logit(Target, Distractor))

d_r_nw_dis <- d_r_nw_vs %>% 
  filter(Bias_Target == "Distractor")

# library(lme4)
# m_e <- lmer(
#   elog ~ 
#     (ot1 + ot2 + ot3) * Study * Condition  + 
#     (ot1 + ot2 + ot3 | ResearchID/Condition/Study),
#   data = d_r_nw_dis)
# summary(m_e)
# readr::write_rds(m_e, "me.rds")

m_e <- readr::read_rds("stan_me.rds.gz")
summary(m_e)

d <- tristan::augment_posterior_linpred(m_e, nsamples = 100)


aug <- broom::augment(m_e, d_r_nw_dis) %>% 
  as_tibble()
aug <- d

diff_aug <- aug %>% 
  mutate(
    Prop = plogis(elog),
    PropFitted = plogis(.posterior_value)) %>% 
  select(.draw, Study:Condition, Time, Prop, PropFitted, elog, .posterior_value) %>% 
  tidyr::gather("measure", "value", elog, .posterior_value, Prop, PropFitted) %>% 
  tidyr::spread(Condition, value) %>% 
  mutate(`real - nonsense` = real - nonsense) %>% 
  tidyr::gather("Condition", "value", nonsense:`real - nonsense`) %>% 
  tidyr::spread(measure, value)

diff_aug %>% 
  select(-.draw) %>% 
  tidyr::nest(.posterior_value:PropFitted)

ggplot(diff_aug) + 
  aes(x = Time, y = Prop , color = Condition, linetype = Condition) +
  geom_hline(color = "white", size = 2, yintercept = .5) +
  # stat_summary() + 
  stat_summary(aes(y = PropFitted), fun.data = median_hilow) +
  facet_wrap("Study")

diff_aug %>% 
  filter(Condition == "real - nonsense") %>% 
  ggplot() + 
    aes(x = Time, y = Prop) +
    geom_hline(color = "white", size = 2, yintercept = 0) +
    stat_summary(fun.data = median_hilow, size = 1.5,
                 geom = "linerange",
                 fun.args = list(conf.int = .5)) +
    stat_summary(fun.data = median_hilow, 
                 fun.args = list(conf.int = .9)) +
    geom_hline(color = "white", size = .25, yintercept = 0) +
    facet_wrap("Study")


diff_aug %>% 
  tjmisc::sample_n_of(4, ResearchID) %>% 
  ggplot() + 
    aes(x = Time, y = Prop , color = Condition, linetype = Condition) +
    geom_hline(color = "white", size = 2, yintercept = .5) +
    stat_summary(aes(y = Prop, group = interaction(Study, Condition)), geom = "line", fun.y = mean) +
    facet_wrap("ResearchID")
  

# m <- glmer(
#   cbind(Target, Distractor) ~ 
#     (ot1 + ot2 + ot3) * Study + 
#     (ot1 | ResearchID) +
#     (ot1 + ot2 + ot3 | ResearchID:Study),
#   family = binomial,
#   data = d_r_ui)

```










```{r explore-rts, eval = FALSE}
da <- readr::read_csv("./data/aim2-screened.csv.gz")

rts <- da %>% 
  filter(
    Bias_Fam %in% c("Familiar", "Unfamiliar"), 
    0 <= Time,
    GazeByImageAOI %in% c("Target", "Distractor")) %>% 
  group_by(
    Study, Condition, ResearchID, TrialNo, TrialID, 
    Bias_ImageAOI, GazeByImageAOI) %>% 
  summarise(FirstLook = min(Time)) %>% 
  ungroup()

rts %>% 
  filter(
    200 <= FirstLook,
    Condition == "real",
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor") %>% 
  ggplot() + 
    aes(x = FirstLook) + 
    geom_histogram() +
    facet_wrap(Study ~ Condition)

rts %>% 
  filter(
    200 <= FirstLook,
    Condition == "real",
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor") %>% 
  ggplot() + 
    aes(x = Study, y = FirstLook) + 
    geom_point(position = position_jitter(width = .1)) + 
    stat_summary(color = "red") + 
    scale_y_log10()

rts %>% 
  filter(
    200 <= FirstLook,
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor",
    Condition != "nonsense") %>% 
  ggplot() + 
    aes(y = interaction(Study, Condition), x = FirstLook) + 
    ggridges::stat_density_ridges()  

rts %>% 
  filter(
    200 <= FirstLook,
    Condition == "real",
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor") %>% 
  ggplot() + 
    aes(x = Study, y = FirstLook) + 
    # geom_point(position = position_jitter(width = .1)) + 
    stat_summary(
      aes(group = ResearchID), 
      position = position_jitter(width = .2)) + 
    stat_summary(color = "red") + 
    scale_y_log10()

d_test <- rts %>% 
  filter(
    200 <= FirstLook,
    Condition == "real",
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor") %>% 
  mutate(S = factor(Study, c("TimePoint2", "TimePoint1", "TimePoint3")))

library(lme4)
try <- lmer(log(FirstLook) ~ S + (1 | ResearchID/S), d_test)
summary(try)

```

```{r bayes-dead-end, eval = FALSE, include = FALSE}
# library(rstanarm)
# try <- stan_glmer(
#   log(FirstLook) ~ S + (1 | ResearchID/S), 
#   d_test, 
#   family = gaussian(),
#   prior = normal(0, 1),
#   chains = 1, 
#   iter = 1000)
# summary(try)
# 
# pp_check(try)
# pp <- posterior_predict(try)
# t1 <- which(d_test$Study == "TimePoint1")
# t2 <- which(d_test$Study == "TimePoint2")
# t3 <- which(d_test$Study == "TimePoint3")
# 
# bayesplot::ppc_dens_overlay(log(d_test$FirstLook[t1]), yrep = pp[, t1], size = 0.25, alpha = 0.7, trim = FALSE,
#   bw = "nrd0", adjust = 1, kernel = "gaussian", n_dens = 1024)
# 
# bayesplot::ppc_dens_overlay(
#   log(d_test$FirstLook[t1]), 
#   yrep = pp[sample(1:500, size = 50), t1])
# 
# bayesplot::ppc_dens_overlay(
#   d_test$FirstLook[t1], 
#   yrep = exp(pp[sample(1:500, size = 50), t1])) + 
#   ggtitle("FirstLook ~ Study + (1 | ID/Study), Age 3, Real, Unfamiliar Initial") + 
#   labs(caption = "Density of posterior predictions")
# ggsave("misc/bayes-rts-real-age3-unfam.png")
# 
# bayesplot::ppc_dens_overlay(
#   d_test$FirstLook[t2], 
#   yrep = exp(pp[sample(1:500, size = 50), t2])) + 
#   ggtitle("FirstLook ~ Study + (1 | ID/Study), Age 4, Real, Unfamiliar Initial") + 
#   labs(caption = "Density of posterior predictions")
# ggsave("misc/bayes-rts-real-age4-unfam.png")
# 
# 
# bayesplot::ppc_dens_overlay(
#   d_test$FirstLook[t3], 
#   yrep = exp(pp[sample(1:500, size = 50), t3])) + 
#   ggtitle("FirstLook ~ Study + (1 | ID/Study), Age 5, Real, Unfamiliar Initial") + 
#   labs(caption = "Density of posterior predictions")
# ggsave("misc/bayes-rts-real-age5-unfam.png")
# 
```






















<!-- Observations: -->

<!--   - Probability of looking to familiar image given real word increased in -->
<!--     year 3. Kind of unexpected that they could improve noticeably on this simple -->
<!--     two-image task. -->
<!--   - Probability of looking to unfamiliar given a nonword increases each year. -->
<!--   - Probability of looking to familiar given a mispronunciation increased -->
<!--   - 250 to 1500 looks like a reasonable analysis window. -->
<!--   - Before the onset of the target word, there appears to be some looking -->
<!--     preferences—maybe—for the familiar at timepoint 1 and unfamiliar -->
<!--     in timepoint 3. -->
<!--   - The "peak" growth curve feature will need to be flipped for the nonword -->
<!--     trials. -->
