Aim 2: Notebook
===================




## Coding Notebook

```{r include = FALSE}
knitr::read_chunk("./helpers.R")
if (interactive()) source("./helpers.R")
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r helpers, message = FALSE, warning = FALSE}
```

```{r, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

```{r}
d <- readr::read_csv("./data/aim2-model-ready.csv.gz") %>% 
  filter(!is.na(Bias_Fam)) %>% 
  filter(300 <= Time) %>% 
  select(-starts_with("ot")) %>% 
  polypoly::poly_add_columns(
    Time, degree = 3, scale_width = 1, prefix = "ot")

ggplot(d) + 
  aes(x = Time, y = Prop, color = Bias_Fam) + 
  facet_wrap(Condition ~ Study) + 
  geom_line(aes(group = interaction(ResearchID, Bias_Fam)), alpha = .1) +
  guides(color = FALSE) + 
  scale_color_viridis_d(end = .8) + 
  stat_smooth(method = "gam", formula = y ~ s(x), se = FALSE)
```



```{r}
# Flip things so that the nonword and real-word curves go upward
d_r_ui <- d %>% 
  filter(Condition == "real", Bias_Fam == "Unfamiliar") %>% 
  mutate(elog = empirical_logit(Target, Distractor))

d_bias_target <- tibble::tribble(
  ~Condition, ~Bias_Fam, ~Bias_Target,
  "nonsense", "Familiar", "Distractor",
  "nonsense", "Unfamiliar", "Target",
  "real", "Familiar", "Target",
  "real", "Unfamiliar", "Distractor")

d_r_nw_vs <- d %>% 
  select(-Primary, -.response_def, -Prop, -PropSE) %>% 
  filter(Condition != "MP") %>% 
  rename(Unfamiliar = Distractor, Familiar = Target) %>% 
  mutate(
    Target = ifelse(Condition == "nonsense", Unfamiliar, Familiar), 
    Distractor = ifelse(Condition == "nonsense", Familiar, Unfamiliar),
    Trials = Target + Distractor) %>% 
  left_join(d_bias_target) %>% 
  mutate(elog = empirical_logit(Target, Distractor))

d_r_nw_dis <- d_r_nw_vs %>% 
  filter(Bias_Target == "Distractor")

d_r_nw_dis %>% 
  filter(Trials < 4) %>% 
  distinct(Study, ResearchID) %>% 
  inner_join(d_r_nw_dis, .) %>% 
  ggplot() + 
    aes(x = Time, y = plogis(elog), color = Condition) + 
    stat_summary()

d_r_nw_dis %>% 
  # filter(Trials > 4) %>% 
  # distinct(Study, ResearchID) %>% 
  # inner_join(d_r_nw_dis, .) %>% 
  ggplot() + 
    aes(x = Time, y = plogis(elog), color = Condition) + 
    stat_summary()


study_child_with_empty_cells <- d_r_nw_dis %>% 
  filter(Trials < 4) %>% 
  distinct(Study, ResearchID)

d_r_nw_dis <- d_r_nw_dis %>% 
  anti_join(study_child_with_empty_cells)
```

```{r}
library(brms)

test_data_1 <- d_r_nw_dis %>%
  filter(Study == "TimePoint1") %>% 
  select(
    Study, ResearchID, Condition, Time, ot1:ot3, Target, Distractor, 
    Trials, elog)

test_data_2 <- d_r_nw_dis %>%
  filter(Study == "TimePoint2") %>% 
  select(
    Study, ResearchID, Condition, Time, ot1:ot3, Target, Distractor, 
    Trials, elog)

test_data_3 <- d_r_nw_dis %>%
  filter(Study == "TimePoint3") %>% 
  select(
    Study, ResearchID, Condition, Time, ot1:ot3, Target, Distractor, 
    Trials, elog)

# Fit a hierarchical logistic regression model
test_formula <- bf(
  Target | trials(Trials) ~ 
    (ot1 + ot2 + ot3) * Condition + 
    (ot1 + ot2 + ot3 | ResearchID/Condition), 
  family = binomial)

priors <- c(
  set_prior(class = "Intercept", "normal(0, 1)"),
  set_prior(class = "b", "normal(0, 1)"),
  set_prior(class = "b", coef = "ot1", "normal(0, 2)"),
  set_prior(class = "cor", "lkj(2)"),
  set_prior(class = "sd", "student_t(3, 0, 5)"))






# test_m_tp2 <- brm(
#   formula = test_formula,
#   data = test_data_2,
#   prior = priors,
#   chains = 4,
#   cores = 4,
#   control = list(adapt_delta = .95))
# readr::write_rds(test_m_tp2, "tp2_mp.rds.gz")

# test_m_tp3 <- brm(
#   formula = test_formula,
#   data = test_data_3,
#   prior = priors,
#   chains = 4,
#   cores = 4,
#   control = list(adapt_delta = .95))
# readr::write_rds(test_m_tp3, "tp3_mp.rds.gz")

# test_formula_all <- bf(
#   Target | trials(Trials) ~ 
#     (ot1 + ot2 + ot3) * Condition * Study + 
#     (ot1 + ot2 + ot3 | ResearchID/Condition/Study), 
#   family = binomial)
# 
# test_m_all <- brm(
#   formula = test_formula_all,
#   data = d_r_nw_dis,
#   prior = priors,
#   chains = 4,
#   cores = 4,
#   control = list(adapt_delta = .95))
# readr::write_rds(test_m_all, "all_mp.rds.gz")






test_m_tp1 <- readr::read_rds("tp1_mp_2.rds.gz")
test_m_tp2 <- readr::read_rds("tp2_mp.rds.gz")
test_m <- test_m_tp2

summary(test_m)
prior_summary(test_m)

p <- marginal_effects(test_m)
# plot(p)

test_data <- test_data_2
sss <- test_data$ResearchID %>% unique() %>% sample(8)

n1 <- test_data %>% 
  distinct(Condition, Time, ot1, ot2, ot3) %>% 
  tidyr::crossing(., ResearchID = sss) %>% 
  mutate(Trials = 30)

n2 <- test_data %>% 
  distinct(Condition, Time, ot1, ot2, ot3) %>% 
  tidyr::crossing(., ResearchID = "Simulated new participants (500)") %>% 
  mutate(Trials = 30)

augment_linpred <- function(model, data, ...) {
  model %>% 
    posterior_linpred(newdata = data, ...) %>% 
    as.data.frame() %>% 
    as_tibble() %>% 
    rlang::set_names(seq_len(nrow(data))) %>% 
    tibble::rowid_to_column(".draw") %>% 
    tidyr::gather(".observation", ".posterior_value", -.draw) %>% 
    mutate(.observation = as.numeric(.observation)) %>% 
    left_join(
      data %>% tibble::rowid_to_column(".observation"),
      by = ".observation")
}

pl1 <- augment_linpred(
  test_m, n1, allow_new_levels = TRUE, re_formula = NULL, nsamples = 200)

pl2 <- augment_linpred(
  test_m, n2, allow_new_levels = TRUE, re_formula = NULL, nsamples = 500)

library("ggthemes")
inv_logit <- function(x) 1 / (1 + exp(-x))
pl <- bind_rows(pl1, pl2)

ggplot(pl) + 
  aes(x = Time, y = inv_logit(.posterior_value), color = Condition) +
  geom_line(
    aes(group = interaction(.draw, Condition)), 
    alpha = .05) +
  geom_line(
    aes(y = Target / Trials, group = Condition),
    data = test_data %>% filter(ResearchID %in% sss),
    color = "grey20") + 
  facet_wrap("ResearchID") + 
  # theme_solarized_2(light = FALSE) + 
  # scale_color_solarized() + 
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  labs(
    title = "Example observed means and 200 posterior fits",
    x = constants$x_time,
    y = constants$y_prop_target,
    caption = "Sample of 8 of 155 total participants")

diffs <- pl2 %>% 
  select(.draw, .posterior_value, Condition, Time) %>% 
  tidyr::spread(Condition, .posterior_value) %>% 
  mutate(
    nonsense_prop = plogis(nonsense), 
    real_prop = plogis(real),
    `real - nonsense` = real_prop - nonsense_prop) %>% 
  select(.draw, Time, nonsense_prop, real_prop, `real - nonsense`)

ggplot(diffs) + 
  aes(x = Time, y = `real - nonsense`) + 
  geom_line(aes(group = .draw), alpha = .1) + 
  stat_summary(fun.data = median_hilow)


pl3 <- augment_linpred(
  test_m, n2, allow_new_levels = TRUE, re_formula = NA, nsamples = 500)


diffs_2 <- pl3 %>% 
  select(.draw, .posterior_value, Condition, Time) %>% 
  tidyr::spread(Condition, .posterior_value) %>% 
  mutate(
    nonsense_prop = plogis(nonsense), 
    real_prop = plogis(real),
    `real - nonsense` = real_prop - nonsense_prop) %>% 
  select(.draw, Time, nonsense_prop, real_prop, `real - nonsense`)

ggplot(diffs_2) + 
  aes(x = Time, y = `real - nonsense`) + 
  geom_line(aes(group = .draw), alpha = .1) + 
  stat_summary(fun.data = median_hilow)

emp_diffs <- test_data_2 %>% 
  select(ResearchID, elog, Condition, Time) %>% 
  tidyr::spread(Condition, elog) %>% 
  mutate(
    nonsense_prop = plogis(nonsense), 
    real_prop = plogis(real),
    `real - nonsense` = real_prop - nonsense_prop) %>% 
  select(ResearchID, Time, nonsense_prop, real_prop, `real - nonsense`)

ggplot(emp_diffs) + 
  aes(x = Time, y = `real - nonsense`) + 
  geom_line(aes(group = ResearchID), alpha = .1) + 
  stat_summary(fun.data = mean_cl_boot)



pl2 %>% 
  ggplot() + 
    aes(x = Time, y = .posterior_value, color = Condition) + 
    stat_summary(fun.data = median_hilow)

pl4 <- augment_linpred(
  test_m, n1, allow_new_levels = TRUE, re_formula = NULL, nsamples = 500)


diffs_4 <- pl4 %>% 
  select(.draw, ResearchID, .posterior_value, Condition, Time) %>% 
  tidyr::spread(Condition, .posterior_value) %>% 
  mutate(
    nonsense_prop = plogis(nonsense), 
    real_prop = plogis(real),
    `real - nonsense` = real_prop - nonsense_prop) %>% 
  select(.draw, ResearchID, Time, nonsense_prop, real_prop, `real - nonsense`)

n1 %>% 
  select(-Trials) %>% 
  inner_join()
ggplot(diffs_4) + 
  aes(x = Time, y = `real - nonsense`) + 
  stat_summary(aes(group = .draw), fun.y = mean, geom = "line") + 
  stat_summary(data =)

```


```{r}
# library(rstanarm)
# options(mc.cores = parallel::detectCores())

# m_e <- stan_glmer(
#   cbind(Target, Distractor) ~ 
#     (ot1 + ot2 + ot3) * Study * Condition  + 
#     (ot1 + ot2 + ot3 | ResearchID/Condition/Study),
#   family = binomial,
#   prior = normal(0, 2, autoscale = FALSE),
#   prior_intercept = normal(0, 2, autoscale = FALSE),
#   prior_covariance = decov(2, 1, 1),
#   data = d_r_nw_dis)
# readr::write_rds(m_e, "stan_me.rds")
# readr::write_rds(m_e, "stan_me.rds.gz")
```


```{r}
m_e <- readr::read_rds("stan_me.rds.gz")
d <- posterior_linpred(m_e, draws = 1000)
ncol(d)
nrow(d_r_nw_dis)

dlong <- d %>% 
  as.data.frame() %>% 
  tibble::rowid_to_column(".draw") %>% 
  as_tibble() %>% 
  tidyr::gather(".observation", ".estimate", -.draw) %>% 
  mutate(.observation = as.numeric(.observation))

big_big <- d_r_nw_dis %>% 
  tibble::rowid_to_column(".observation") %>% 
  select(.observation:Condition, Time) %>% 
  left_join(dlong) %>% 
  select(-.observation) %>% 
  tidyr::spread(Condition, .estimate)

big_big <- big_big %>% 
  mutate(
    diff_prop = plogis(real) - plogis(nonsense), 
    real = plogis(real), nonsense = plogis(nonsense))

big_big <- big_big %>% 
  tidyr::gather("Condition", "value", nonsense:diff_prop) 

library(ggplot2)
big_big %>% 
  mutate(
    Condition = ifelse(Condition == "diff_prop", "Real - Nonword", Condition),
    Condition = ifelse(Condition == "nonsense", "Nonword", Condition),
    Condition = ifelse(Condition == "real", "Real word", Condition)) %>%
  filter(Study == "TimePoint1") %>% 
  group_by(Study, .draw, Time, Condition) %>% 
  summarise(value = median(value)) %>% 
  ggplot() + 
    aes(x = Time, y = value) + 
    stat_summary(fun.data = median_hilow) + 
    facet_wrap("Condition")

head(d[1, 1:5])
library(bayesplot)
pp_check(test_m, nsample = 200)


```




```{r}

diff_aug <- aug %>% 
  mutate(
    Prop = plogis(elog),
    PropFitted = plogis(.fitted)) %>% 
  select(Study:Condition, Time, Prop, PropFitted, elog, .fitted) %>% 
  tidyr::gather("measure", "value", elog, .fitted, Prop, PropFitted) %>% 
  tidyr::spread(Condition, value) %>% 
  mutate(`real - nonsense` = real - nonsense) %>% 
  tidyr::gather("Condition", "value", nonsense:`real - nonsense`) %>% 
  tidyr::spread(measure, value)

ggplot(diff_aug) + 
  aes(x = Time, y = Prop , color = Condition, linetype = Condition) +
  geom_hline(color = "white", size = 2, yintercept = .5) +
  stat_summary() + 
  stat_summary(aes(y = PropFitted), geom = "line", fun.y = mean) +
  facet_wrap("Study")

diff_aug %>% 
  filter(Condition == "real - nonsense") %>% 
  ggplot() + 
    aes(x = Time, y = Prop) +
    geom_hline(color = "white", size = 2, yintercept = 0) +
    stat_summary(fun.data = median_hilow, size = 1.5,
                 geom = "linerange",
                 fun.args = list(conf.int = .5)) +
    stat_summary(fun.data = median_hilow, 
                 fun.args = list(conf.int = .9)) +
    geom_hline(color = "white", size = .25, yintercept = 0) +
    facet_wrap("Study")


```






```{r explore-rts, eval = FALSE}
da <- readr::read_csv("./data/aim2-screened.csv.gz")

rts <- da %>% 
  filter(
    Bias_Fam %in% c("Familiar", "Unfamiliar"), 
    0 <= Time,
    GazeByImageAOI %in% c("Target", "Distractor")) %>% 
  group_by(
    Study, Condition, ResearchID, TrialNo, TrialID, 
    Bias_ImageAOI, GazeByImageAOI) %>% 
  summarise(FirstLook = min(Time)) %>% 
  ungroup()

rts %>% 
  filter(
    200 <= FirstLook,
    Condition == "real",
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor") %>% 
  ggplot() + 
    aes(x = FirstLook) + 
    geom_histogram() +
    facet_wrap(Study ~ Condition)

rts %>% 
  filter(
    200 <= FirstLook,
    Condition == "real",
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor") %>% 
  ggplot() + 
    aes(x = Study, y = FirstLook) + 
    geom_point(position = position_jitter(width = .1)) + 
    stat_summary(color = "red") + 
    scale_y_log10()

rts %>% 
  filter(
    200 <= FirstLook,
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor",
    Condition != "nonsense") %>% 
  ggplot() + 
    aes(y = interaction(Study, Condition), x = FirstLook) + 
    ggridges::stat_density_ridges()  

rts %>% 
  filter(
    200 <= FirstLook,
    Condition == "real",
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor") %>% 
  ggplot() + 
    aes(x = Study, y = FirstLook) + 
    # geom_point(position = position_jitter(width = .1)) + 
    stat_summary(
      aes(group = ResearchID), 
      position = position_jitter(width = .2)) + 
    stat_summary(color = "red") + 
    scale_y_log10()

d_test <- rts %>% 
  filter(
    200 <= FirstLook,
    Condition == "real",
    Bias_ImageAOI != GazeByImageAOI,
    Bias_ImageAOI == "Distractor") %>% 
  mutate(S = factor(Study, c("TimePoint2", "TimePoint1", "TimePoint3")))

library(lme4)
try <- lmer(log(FirstLook) ~ S + (1 | ResearchID/S), d_test)
summary(try)

```

```{r bayes-dead-end, eval = FALSE, include = FALSE}
# library(rstanarm)
# try <- stan_glmer(
#   log(FirstLook) ~ S + (1 | ResearchID/S), 
#   d_test, 
#   family = gaussian(),
#   prior = normal(0, 1),
#   chains = 1, 
#   iter = 1000)
# summary(try)
# 
# pp_check(try)
# pp <- posterior_predict(try)
# t1 <- which(d_test$Study == "TimePoint1")
# t2 <- which(d_test$Study == "TimePoint2")
# t3 <- which(d_test$Study == "TimePoint3")
# 
# bayesplot::ppc_dens_overlay(log(d_test$FirstLook[t1]), yrep = pp[, t1], size = 0.25, alpha = 0.7, trim = FALSE,
#   bw = "nrd0", adjust = 1, kernel = "gaussian", n_dens = 1024)
# 
# bayesplot::ppc_dens_overlay(
#   log(d_test$FirstLook[t1]), 
#   yrep = pp[sample(1:500, size = 50), t1])
# 
# bayesplot::ppc_dens_overlay(
#   d_test$FirstLook[t1], 
#   yrep = exp(pp[sample(1:500, size = 50), t1])) + 
#   ggtitle("FirstLook ~ Study + (1 | ID/Study), Age 3, Real, Unfamiliar Initial") + 
#   labs(caption = "Density of posterior predictions")
# ggsave("misc/bayes-rts-real-age3-unfam.png")
# 
# bayesplot::ppc_dens_overlay(
#   d_test$FirstLook[t2], 
#   yrep = exp(pp[sample(1:500, size = 50), t2])) + 
#   ggtitle("FirstLook ~ Study + (1 | ID/Study), Age 4, Real, Unfamiliar Initial") + 
#   labs(caption = "Density of posterior predictions")
# ggsave("misc/bayes-rts-real-age4-unfam.png")
# 
# 
# bayesplot::ppc_dens_overlay(
#   d_test$FirstLook[t3], 
#   yrep = exp(pp[sample(1:500, size = 50), t3])) + 
#   ggtitle("FirstLook ~ Study + (1 | ID/Study), Age 5, Real, Unfamiliar Initial") + 
#   labs(caption = "Density of posterior predictions")
# ggsave("misc/bayes-rts-real-age5-unfam.png")
# 
```
















```{r}

test_f <- bf(
  elog ~ 
    (ot1 + ot2 + ot3) * Condition + 
    (ot1 + ot2 + ot3 | ResearchID/Condition), 
  family = gaussian)

prior_intercept <- set_prior("normal(0, 1)", class = "Intercept")
prior_b <- set_prior("normal(0, 1)", class = "b")
prior_ot1 <- set_prior("normal(0, 2)", class = "b", coef = "ot1")
prior_cor <- set_prior("lkj(2)", class = "cor")
prior_sd <- set_prior("student_t(3, 0, 1)", class = "sd")
prior_sigma <- set_prior("student_t(3, 0, 1)", class = "sigma")
priors <- c(prior_intercept, prior_b, prior_ot1, prior_cor, prior_sd, prior_sigma)

```






<!-- Observations: -->

<!--   - Probability of looking to familiar image given real word increased in -->
<!--     year 3. Kind of unexpected that they could improve noticeably on this simple -->
<!--     two-image task. -->
<!--   - Probability of looking to unfamiliar given a nonword increases each year. -->
<!--   - Probability of looking to familiar given a mispronunciation increased -->
<!--   - 250 to 1500 looks like a reasonable analysis window. -->
<!--   - Before the onset of the target word, there appears to be some looking -->
<!--     preferences—maybe—for the familiar at timepoint 1 and unfamiliar -->
<!--     in timepoint 3. -->
<!--   - The "peak" growth curve feature will need to be flipped for the nonword -->
<!--     trials. -->
