Sensitivity to mispronunciations
=======================================================================

```{r, include = FALSE}
knitr::read_chunk("./helpers.R")
if (interactive()) source("./helpers.R")
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r helpers, message = FALSE, warning = FALSE}
```

```{r, include = FALSE}
# knitr::opts_chunk$set(cache = TRUE)
constants$cap_emp_and_sim <- 
  "Points: Emprical means ± SE.
Ribbons: Mean ± 95% CI for 1000 simulated children."



```

```{r}
d_raw <- readr::read_csv("./data/aim2-model-ready.csv.gz") %>% 
  select(-starts_with("ot"))
  # filter(!is.na(Bias_Fam)) %>% 
  # filter(0 <= Time) %>% 
# %>% 
#   polypoly::poly_add_columns(
#     Time, degree = 3, scale_width = 1, prefix = "ot")

# Flip things so that the nonword and real-word curves go upward
d_raw_mp <- d_raw %>% 
  filter(Condition == "MP") 

d_raw_all <- d_raw %>% 
  filter(Condition == "MP") %>% 
  group_by(Study, ResearchID, Time) %>% 
  summarise(
    Bias_Fam = "all",
    Distractor = sum(Distractor),
    Target = sum(Target),
    Looks = sum(Looks),
    Elsewhere = sum(Elsewhere),
    Missing = sum(Missing), 
    Primary = sum(Primary),
    Trials = Primary + Distractor,
    Prop = Primary / Trials,
    PropSE = se_prop(Prop, Trials),
    PropNA = Missing / Looks
  )

d_raw_mp %>% 
  bind_rows(d_raw_all) %>%
  ggplot() + 
    aes(x = Time, y = Prop, color = Study) + 
    stat_summary() + 
    facet_grid(~ Bias_Fam)

d <- d_raw %>% 
  select(-starts_with("ot")) %>% 
  filter(Condition == "MP", !is.na(Bias_Fam), 300 <= Time) %>% 
  mutate(Trials = Target + Distractor) %>% 
  polypoly::poly_add_columns(
    Time, degree = 3, scale_width = 1, prefix = "ot")

d %>% 
  tjmisc::sample_n_of(20, ResearchID) %>% 
  ggplot() + 
    aes(x = Time, y = Prop) + 
    geom_line(aes(group = interaction(ResearchID))) +
    facet_grid(Study ~ Bias_Fam) + 
    stat_summary() + 
  labs(
    title = "Results for 20 random children")

study_child_with_empty_cells <- d %>% 
  filter(Trials < 4) %>% 
  distinct(Study, ResearchID, Bias_Fam)

# study_counts <- study_child_with_empty_cells %>% 
#   count(Study) %>% 
#   split(.$Study) %>% 
#   lapply(pull, n) %>% 
#   set_names(stringr::str_replace, "TimePoint", "T")

d <- d %>% 
  anti_join(study_child_with_empty_cells)

d_u <- d %>% filter(Bias_Fam == "Unfamiliar")
d_f <- d %>% filter(Bias_Fam == "Familiar")
# m_u <- glmer(
#   cbind(Target, Distractor) ~ 
#     (ot1 + ot2 + ot3) * Study + 
#     (ot1 + ot2 + ot3 | ResearchID/Study),
#   family = binomial,
#   data = d_u
# ) 
# 
# summary(m_u)
# readr::write_rds(m_u, "m_u_all.rds.gz")

library(brms)

# Fit a hierarchical logistic regression model
formula <- bf(
  Target | trials(Trials) ~ 
    (1 + ot1 + ot2 + ot3) * Study + 
    (1 + ot1 + ot2 + ot3 | ResearchID/Study), 
  family = binomial)

priors <- c(
  set_prior(class = "Intercept", "normal(0, 1)"),
  set_prior(class = "b", "normal(0, 1)"),
  set_prior(class = "b", coef = "ot1", "normal(0, 2)"),
  set_prior(class = "cor", "lkj(2)"),
  set_prior(class = "sd", "student_t(7, 0, 2)"))

# mp_unfam <- brm(
#   formula = formula,
#   data = d_u,
#   prior = priors,
#   chains = 4,
#   cores = 4,
#   control = list(adapt_delta = .99, max_treedepth = 15))
# 
# # Save the output
# readr::write_rds(mp_unfam, "mp_unfam2.rds.gz")
mp_unfam <- readr::read_rds("data/aim2-mp-unfam2.rds.gz")
mp_unfam

# fits <- augment_linpred(mp_unfam, d_u, nsamples = 100)
# 
# fits %>% 
#   sample_n_of(4, ResearchID) %>% 
#   ggplot() + 
#   aes(x = Time, y = Prop, color = Study) + 
#   geom_line() + 
#   geom_line(
#     aes(
#       group = interaction(Study, .draw, ResearchID),
#       y = plogis(.posterior_value)),
#     alpha = .05) + 
#   facet_wrap("ResearchID") 

# # Population averages vs average of lines in sample
# fits2 <- augment_linpred(mp_unfam, d_u, re_formula = NA, nsamples = 100)
# fits2 %>% 
#   ggplot() + 
#   aes(x = Time, y = Prop, color = Study) + 
#   stat_summary() +
#   geom_line(
#     aes(
#       group = interaction(Study, .draw),
#       y = plogis(.posterior_value)),
#     data = . %>% filter(ResearchID == "036L"),
#     alpha = .05) + 
#   labs(
#     caption = "fixed-effect predictions")
# 

# # Average of posterior fits of lines in sample vs average of lines in sample
# fits %>% 
#   ggplot() + 
#   aes(x = Time, y = Prop, color = Study) + 
#   stat_summary() +
#   stat_summary(
#     aes(group = interaction(Study, .draw), y = plogis(.posterior_value)),
#     geom = "line",
#     fun.y = "mean",
#     alpha = .05) + 
#   labs(
#     caption = "averages of posterior fits")

newdata <- d_u %>% 
  distinct(Time, ot1, ot2, ot3, Study) %>% 
  mutate(ResearchID = "zzz", Target = 0, Trials = 30)

m_u_new_fits <- augment_linpred(
  mp_unfam, newdata, nsamples = 1000, allow_new_levels = TRUE) %>% 
  mutate(Study = convert_study_to_age(Study)) 

df_u_label <- tibble::tribble(
  ~Study, ~Time, ~Prop,
  "Age 3", 1050, .42,
  # "Age 4", 1000, .42,
  "Age 5", 1300, .73
)

d_u_plotting <- d_u %>% 
  mutate(Study = convert_study_to_age(Study)) 


ggplot(d_u_plotting) + 
  aes(x = Time, y = Prop, color = Study) + 
  geom_hline(yintercept = .5, size = 2, color = "white") +
  stat_summary(fun.data = mean_se, geom = "pointrange") + 
  stat_summary(
    aes(group = Study, fill = Study, y = plogis(.posterior_value)),
    data = m_u_new_fits,
    fun.data = mean_cl_normal,
    geom = "ribbon",
    alpha = .3,
    color = NA) + 
  stat_summary(
    aes(group = Study, y = plogis(.posterior_value)),
    data = m_u_new_fits,
    fun.y = mean,
    geom = "line") + 
  geom_text(
    aes(label = Study),
    data = df_u_label,
    size = 5, 
    family = "Lato Semibold") +
  geom_text(
    aes(label = label),
    data = data_frame(
      Time = 425, 
      Prop = .11, 
      label = constants$note_mp_unfam),
    size = 3, 
    hjust = 0,
    color = constants$col_off_black,
    family = "Lato") +
  scale_fill_study() + 
  scale_color_study() + 
  expand_limits(y = .76) +
  guides(color = FALSE, fill = FALSE) +
  theme(plot.caption = element_text(lineheight = 1.2)) +
  labs(
    x = constants$x_time,
    y = constants$y_prop_fam,
    caption = constants$cap_emp_and_sim)



constants








library(bayesplot)
theme_set(theme_teej())
mcmc_intervals(as.matrix(mp_unfam), regex_pars = "b_")
zoo::rollmedian(x, 5, fill = NA)
length(zoo::rollmedian(x, 5))


try2 <- fits %>% 
  tjmisc::sample_n_of(10, .draw) %>% 
  group_by(.draw, Study, ResearchID) %>% 
  mutate(
    med = zoo::rollmedian(.posterior_value, 5, fill = "extend")
  )
  
```

```{r}
mp_fam <- readr::read_rds("data/aim2-mp-fam.rds.gz")

# fits <- augment_linpred(mp_fam, d_f, nsamples = 100)
# 
# fits %>% 
#   sample_n_of(4, ResearchID) %>%
#   # filter(ResearchID == "644L") %>% 
#   ggplot() + 
#   aes(x = Time, y = Prop, color = Study) + 
#   geom_pointrange(aes(ymin = Prop - PropSE, ymax = Prop + PropSE)) + 
#   geom_line(
#     aes(
#       group = interaction(Study, .draw, ResearchID),
#       y = plogis(.posterior_value)),
#     alpha = .05) + 
#   facet_wrap("ResearchID") 
# 
# # Population averages vs average of lines in sample
# fits2 <- augment_linpred(mp_fam, d_f, re_formula = NA, nsamples = 100)
# fits2 %>% 
#   ggplot() + 
#   aes(x = Time, y = Prop, color = Study) + 
#   stat_summary() +
#   geom_line(
#     aes(
#       group = interaction(Study, .draw),
#       y = plogis(.posterior_value)),
#     data = . %>% filter(ResearchID == "036L"),
#     alpha = .05) + 
#   labs(
#     caption = "fixed-effect predictions")
# 
# 
# # Average of posterior fits of lines in sample vs average of lines in sample
# fits %>% 
#   ggplot() + 
#   aes(x = Time, y = Prop, color = Study) + 
#   stat_summary() +
#   stat_summary(
#     aes(group = interaction(Study, .draw), y = plogis(.posterior_value)),
#     geom = "line",
#     fun.y = "mean",
#     alpha = .05) + 
#   labs(
#     caption = "averages of posterior fits")

f_newdata <- d_f %>% 
  distinct(Time, ot1, ot2, ot3, Study) %>% 
  mutate(ResearchID = "zzz", Target = 0, Trials = 30)

m_f_new_fits <- augment_linpred(
  mp_fam, f_newdata, nsamples = 1000, allow_new_levels = TRUE) %>% 
  mutate(Study = convert_study_to_age(Study))

df_f_label <- tibble::tribble(
  ~Study, ~Time, ~Prop,
  "Age 3", 650, .80,
  "Age 4", 1000, .41,
  "Age 5", 1400, .66)

df_f_plotting <- d_f %>% 
  mutate(Study = convert_study_to_age(Study)) 

ggplot(df_f_plotting) + 
  aes(x = Time, y = Prop, color = Study) + 
  geom_hline(yintercept = .5, size = 2, color = "white") +
  stat_summary(fun.data = mean_se, geom = "pointrange") + 
  stat_summary(
    aes(group = Study, fill = Study, y = plogis(.posterior_value)),
    data = m_f_new_fits,
    fun.data = mean_cl_normal,
    geom = "ribbon",
    alpha = .3,
    color = NA) + 
  stat_summary(
    aes(group = Study, y = plogis(.posterior_value)),
    data = m_f_new_fits,
    fun.y = mean,
    geom = "line") + 
  geom_text(
    aes(label = Study),
    data = df_f_label,
    size = 5, 
    family = "Lato Semibold") +
  geom_text(
    aes(label = label),
    data = data_frame(
      Time = 410, 
      Prop = .93, 
      label = constants$note_mp_fam),
    size = 3, 
    hjust = 0,
    color = constants$col_off_black,
    family = "Lato") +
  scale_fill_study() + 
  scale_color_study() + 
  expand_limits(y = .38) +
  guides(color = FALSE, fill = FALSE) +
  theme(plot.caption = element_text(lineheight = 1.2)) +
  labs(
    x = constants$x_time,
    y = constants$y_prop_fam,
    caption = constants$cap_emp_and_sim)






```



```{r lmers, eval = FALSE}
d_u_1 <- d %>% filter(Bias_Fam == "Unfamiliar", Study == "TimePoint1")
m_u_1 <- glmer(
  cbind(Target, Distractor) ~ 
    (ot1 + ot2 + ot3) + 
    (ot1 + ot2 + ot3 | ResearchID),
  family = binomial,
  data = d_u_1
) 
d_u_1 <- d %>% filter(Bias_Fam == "Unfamiliar", Study == "TimePoint1")
m_u_1 <- glmer(
  cbind(Target, Distractor) ~ 
    (ot1 + ot2 + ot3) + 
    (ot1 + ot2 + ot3 | ResearchID),
  family = binomial,
  data = d_u_1
) 

a_u_1 <- broom::augment(m_u_1) %>% 
  select(-1) %>% 
  left_join(d_u_1)

ggplot(a_u_1) + 
  aes(x = Time, y = Prop) + 
  geom_line(
    aes(group = ResearchID), 
    position = position_jitter(height = .01), 
    alpha = .4) + 
  stat_summary(aes(color = "empirical")) + 
  stat_summary(aes(y = plogis(.fixed), color = "fixef")) + 
  stat_summary(aes(y = plogis(.fitted), color = "fitted"))


peak <- a_u_1 %>% 
  group_by(Study, ResearchID) %>% 
  top_n(5, plogis(.fitted)) %>% 
  summarise(
    peak = median(plogis(.fitted))
  )


ggplot(a_u_1) + 
  aes(x = Time, y =  plogis(.fitted)) + 
  geom_line(
    aes(group = ResearchID), 
    # position = position_jitter(height = .01), 
    alpha = .4) 


d_f_1 <- d %>% filter(Bias_Fam == "Familiar", Study == "TimePoint1")
m_f_1 <- glmer(
  cbind(Target, Distractor) ~ 
    (ot1 + ot2 + ot3) + 
    (ot1 + ot2 + ot3 | ResearchID),
  family = binomial,
  data = d_f_1
) 
summary(m_f_1)


a_f_1 <- broom::augment(m_f_1) %>% 
  select(-1) %>% 
  left_join(d_f_1)

ggplot(a_f_1) + 
  aes(x = Time, y =  plogis(.fitted)) + 
  geom_line(
    aes(group = ResearchID), 
    # position = position_jitter(height = .01), 
    alpha = .4) 

ggplot(a_f_1) + 
  aes(x = Time, y = Prop) + 
  geom_line(
    aes(group = ResearchID), 
    position = position_jitter(height = .01), 
    alpha = .4) + 
  stat_summary(aes(color = "empirical")) + 
  stat_summary(aes(y = plogis(.fixed), color = "fixef")) + 
  stat_summary(aes(y = plogis(.fitted), color = "fitted"))




```

