#!/usr/bin/env Rscript

args <- commandArgs(TRUE)

help <- any(c("-h", "--help", "help") %in% args) | length(args) == 0

if (help) {
  args <- "help"
  cat(
"Usage: doit [commands]

Commands:
  help                 display usage
  install_gh_packages  installs required packages from github
  erase_raw_data       erase all data downloaded from database
  get_et_blocks        download eyetracking block attributes
  get_et_trials        download eyetracking trial attributes
  get_et_looks         download eyetracking looks"
)
}


if ("install_gh_packages" %in% args) {
  source("./R/setup_helpers.R")
  install_github_packages()
}

if (!help)  {
  source("./R/database-helpers.R")
}

if ("erase_raw_data" %in% args) {
  data_raw_dir <- rprojroot::find_rstudio_root_file("data-raw")
  curr_files <- list.files(data_raw_dir, "*.csv",
                           full.names = TRUE, recursive = TRUE)

  could_remove <- file.remove(curr_files)
  removed_files <- curr_files[could_remove]
  msg <- paste0(local_file_path(removed_files), collapse = "\n  ")
  message("Removed:\n  ", msg)

  if (any(!could_remove)) {
    error_files <- curr_files[!could_remove]
    msg <- paste0(local_file_path(error_files), collapse = "\n  ")
    message("Could not remove:\n  ", msg)
  }
}

if ("get_et_blocks" %in% args) {
  get_eyetracking_block_attributes()
}

if ("get_et_trials" %in% args) {
  get_eyetracking_trial_attributes()
}

if ("get_et_looks" %in% args) {
  get_eyetracking_looks()
}



