<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>My dissertation</title>
  <meta name="description" content="My dissertation">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="My dissertation" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="tjmahr/dissertation" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="My dissertation" />
  
  
  

<meta name="author" content="Tristan Mahr">


<meta name="date" content="2018-03-03">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="analysis-of-familiar-word-recognition.html">
<link rel="next" href="entropy-in-familiar-word-recognition.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="assets\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">My dissertation</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Development of word recognition in preschoolers</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#updates"><i class="fa fa-check"></i>Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="scratch-paper.html"><a href="scratch-paper.html"><i class="fa fa-check"></i><b>1</b> Scratch paper</a><ul>
<li class="chapter" data-level="1.1" data-path="scratch-paper.html"><a href="scratch-paper.html#bookdown-cheatsheet"><i class="fa fa-check"></i><b>1.1</b> Bookdown cheatsheet</a><ul>
<li class="chapter" data-level="1.1.1" data-path="scratch-paper.html"><a href="scratch-paper.html#manual-section-label-demo"><i class="fa fa-check"></i><b>1.1.1</b> Cross-references to sections</a></li>
<li class="chapter" data-level="1.1.2" data-path="scratch-paper.html"><a href="scratch-paper.html#cross-references-to-appendices"><i class="fa fa-check"></i><b>1.1.2</b> Cross-references to appendices</a></li>
<li class="chapter" data-level="1.1.3" data-path="scratch-paper.html"><a href="scratch-paper.html#cross-references-to-tables"><i class="fa fa-check"></i><b>1.1.3</b> Cross-references to tables</a></li>
<li class="chapter" data-level="1.1.4" data-path="scratch-paper.html"><a href="scratch-paper.html#figure-references-and-using-text-references-as-captions"><i class="fa fa-check"></i><b>1.1.4</b> Figure references and using text references as captions</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="scratch-paper.html"><a href="scratch-paper.html#custom-blocks"><i class="fa fa-check"></i><b>1.2</b> Custom blocks</a></li>
<li class="chapter" data-level="1.3" data-path="scratch-paper.html"><a href="scratch-paper.html#debug-info"><i class="fa fa-check"></i><b>1.3</b> Debug info</a></li>
</ul></li>
<li class="part"><span><b>Prospectus</b></span></li>
<li class="chapter" data-level="2" data-path="front-matter.html"><a href="front-matter.html"><i class="fa fa-check"></i><b>2</b> Front Matter</a><ul>
<li class="chapter" data-level="" data-path="front-matter.html"><a href="front-matter.html#about-this-document"><i class="fa fa-check"></i>About This Document</a></li>
<li class="chapter" data-level="" data-path="front-matter.html"><a href="front-matter.html#dissertation-committee-members"><i class="fa fa-check"></i>Dissertation Committee Members</a></li>
<li class="chapter" data-level="" data-path="front-matter.html"><a href="front-matter.html#planned-dissertation-format"><i class="fa fa-check"></i>Planned Dissertation Format</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="specific-aims.html"><a href="specific-aims.html"><i class="fa fa-check"></i><b>3</b> Specific Aims</a><ul>
<li class="chapter" data-level="3.1" data-path="specific-aims.html"><a href="specific-aims.html#specific-aim-1-familiar-word-recognition-and-lexical-competition"><i class="fa fa-check"></i><b>3.1</b> Specific Aim 1 (Familiar Word Recognition and Lexical Competition)</a></li>
<li class="chapter" data-level="3.2" data-path="specific-aims.html"><a href="specific-aims.html#specific-aim-2-referent-selection-and-mispronunciations"><i class="fa fa-check"></i><b>3.2</b> Specific Aim 2 (Referent Selection and Mispronunciations)</a></li>
<li class="chapter" data-level="3.3" data-path="specific-aims.html"><a href="specific-aims.html#specific-aim-3-computational-modeling"><i class="fa fa-check"></i><b>3.3</b> Specific Aim 3 (Computational Modeling)</a></li>
<li class="chapter" data-level="3.4" data-path="specific-aims.html"><a href="specific-aims.html#summary"><i class="fa fa-check"></i><b>3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="significance.html"><a href="significance.html"><i class="fa fa-check"></i><b>4</b> Significance</a><ul>
<li class="chapter" data-level="4.1" data-path="significance.html"><a href="significance.html#public-health-significance"><i class="fa fa-check"></i><b>4.1</b> Public Health Significance</a></li>
<li class="chapter" data-level="4.2" data-path="significance.html"><a href="significance.html#scientific-significance"><i class="fa fa-check"></i><b>4.2</b> Scientific Significance</a><ul>
<li class="chapter" data-level="4.2.1" data-path="significance.html"><a href="significance.html#lexical-processing-dynamics"><i class="fa fa-check"></i><b>4.2.1</b> Lexical Processing Dynamics</a></li>
<li class="chapter" data-level="4.2.2" data-path="significance.html"><a href="significance.html#individual-differences-in-word-recognition"><i class="fa fa-check"></i><b>4.2.2</b> Individual Differences in Word Recognition</a></li>
<li class="chapter" data-level="4.2.3" data-path="significance.html"><a href="significance.html#computational-modeling"><i class="fa fa-check"></i><b>4.2.3</b> Computational Modeling</a></li>
<li class="chapter" data-level="4.2.4" data-path="significance.html"><a href="significance.html#summary-1"><i class="fa fa-check"></i><b>4.2.4</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="research-hypotheses.html"><a href="research-hypotheses.html"><i class="fa fa-check"></i><b>5</b> Research Hypotheses</a><ul>
<li class="chapter" data-level="5.1" data-path="research-hypotheses.html"><a href="research-hypotheses.html#specific-aim-1-familiar-word-recognition-and-lexical-competition-1"><i class="fa fa-check"></i><b>5.1</b> Specific Aim 1 (Familiar Word Recognition and Lexical Competition)</a></li>
<li class="chapter" data-level="5.2" data-path="research-hypotheses.html"><a href="research-hypotheses.html#specific-aim-2-referent-selection-and-mispronunciations-1"><i class="fa fa-check"></i><b>5.2</b> Specific Aim 2 (Referent Selection and Mispronunciations)</a></li>
<li class="chapter" data-level="5.3" data-path="research-hypotheses.html"><a href="research-hypotheses.html#specific-aim-3-computational-modeling-1"><i class="fa fa-check"></i><b>5.3</b> Specific Aim 3 (Computational Modeling)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>6</b> Methods</a><ul>
<li class="chapter" data-level="6.1" data-path="methods.html"><a href="methods.html#general-research-design-participants"><i class="fa fa-check"></i><b>6.1</b> General Research Design: Participants</a></li>
<li class="chapter" data-level="6.2" data-path="methods.html"><a href="methods.html#general-eyetracking-procedure"><i class="fa fa-check"></i><b>6.2</b> General Eyetracking Procedure</a><ul>
<li class="chapter" data-level="6.2.1" data-path="methods.html"><a href="methods.html#experiment-administration"><i class="fa fa-check"></i><b>6.2.1</b> Experiment Administration</a></li>
<li class="chapter" data-level="6.2.2" data-path="methods.html"><a href="methods.html#stimuli"><i class="fa fa-check"></i><b>6.2.2</b> Stimuli</a></li>
<li class="chapter" data-level="6.2.3" data-path="methods.html"><a href="methods.html#data-preparation"><i class="fa fa-check"></i><b>6.2.3</b> Data Preparation</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="methods.html"><a href="methods.html#specific-procedure-aim-1-familiar-word-recognition-and-lexical-competition"><i class="fa fa-check"></i><b>6.3</b> Specific Procedure: Aim 1 (Familiar Word Recognition and Lexical Competition)</a></li>
<li class="chapter" data-level="6.4" data-path="methods.html"><a href="methods.html#specific-procedure-aim-2-referent-selection-and-mispronunciations"><i class="fa fa-check"></i><b>6.4</b> Specific Procedure: Aim 2 (Referent Selection and Mispronunciations)</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="outcome-measures.html"><a href="outcome-measures.html"><i class="fa fa-check"></i><b>7</b> Outcome Measures</a><ul>
<li class="chapter" data-level="7.1" data-path="outcome-measures.html"><a href="outcome-measures.html#sample-data"><i class="fa fa-check"></i><b>7.1</b> Sample Data</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analysis.html"><a href="analysis.html"><i class="fa fa-check"></i><b>8</b> Analysis</a><ul>
<li class="chapter" data-level="8.1" data-path="analysis.html"><a href="analysis.html#growth-curve-analysis"><i class="fa fa-check"></i><b>8.1</b> Growth Curve Analysis</a></li>
<li class="chapter" data-level="8.2" data-path="analysis.html"><a href="analysis.html#aim-1-familiar-word-recognition-and-lexical-competition"><i class="fa fa-check"></i><b>8.2</b> Aim 1 (Familiar Word Recognition and Lexical Competition)</a></li>
<li class="chapter" data-level="8.3" data-path="analysis.html"><a href="analysis.html#aim-2-referent-selection-and-mispronunciations"><i class="fa fa-check"></i><b>8.3</b> Aim 2 (Referent Selection and Mispronunciations)</a></li>
<li class="chapter" data-level="8.4" data-path="analysis.html"><a href="analysis.html#aim-3-computational-modeling"><i class="fa fa-check"></i><b>8.4</b> Aim 3 (Computational Modeling)</a><ul>
<li class="chapter" data-level="8.4.1" data-path="analysis.html"><a href="analysis.html#trace-model-architecture"><i class="fa fa-check"></i><b>8.4.1</b> TRACE Model Architecture</a></li>
<li class="chapter" data-level="8.4.2" data-path="analysis.html"><a href="analysis.html#modeling-looking-data"><i class="fa fa-check"></i><b>8.4.2</b> Modeling Looking Data</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Aim 1: Familiar Word Recognition and Lexical Competition</b></span></li>
<li class="chapter" data-level="9" data-path="aim1-method.html"><a href="aim1-method.html"><i class="fa fa-check"></i><b>9</b> Method</a><ul>
<li class="chapter" data-level="9.1" data-path="aim1-method.html"><a href="aim1-method.html#participants"><i class="fa fa-check"></i><b>9.1</b> Participants</a><ul>
<li class="chapter" data-level="9.1.1" data-path="aim1-method.html"><a href="aim1-method.html#special-case-data-screening"><i class="fa fa-check"></i><b>9.1.1</b> Special case data screening</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="aim1-method.html"><a href="aim1-method.html#procedure"><i class="fa fa-check"></i><b>9.2</b> Procedure</a></li>
<li class="chapter" data-level="9.3" data-path="aim1-method.html"><a href="aim1-method.html#experiment-administration-1"><i class="fa fa-check"></i><b>9.3</b> Experiment Administration</a></li>
<li class="chapter" data-level="9.4" data-path="aim1-method.html"><a href="aim1-method.html#stimuli-1"><i class="fa fa-check"></i><b>9.4</b> Stimuli</a></li>
<li class="chapter" data-level="9.5" data-path="aim1-method.html"><a href="aim1-method.html#data-screening"><i class="fa fa-check"></i><b>9.5</b> Data screening</a></li>
<li class="chapter" data-level="9.6" data-path="aim1-method.html"><a href="aim1-method.html#prepare-the-dataset-for-modeling"><i class="fa fa-check"></i><b>9.6</b> Prepare the dataset for modeling</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html"><i class="fa fa-check"></i><b>10</b> Analysis of familiar word recognition</a><ul>
<li class="chapter" data-level="10.1" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#growth-curve-analysis-1"><i class="fa fa-check"></i><b>10.1</b> Growth curve analysis</a><ul>
<li class="chapter" data-level="10.1.1" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#growth-curve-features-as-measures-of-word-recognition-performance"><i class="fa fa-check"></i><b>10.1.1</b> Growth curve features as measures of word recognition performance</a></li>
<li class="chapter" data-level="10.1.2" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#year-over-year-changes-in-word-recognition"><i class="fa fa-check"></i><b>10.1.2</b> Year over year changes in word recognition</a></li>
<li class="chapter" data-level="10.1.3" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#exploring-plausible-ranges-of-performance-over-time"><i class="fa fa-check"></i><b>10.1.3</b> Exploring plausible ranges of performance over time</a></li>
<li class="chapter" data-level="10.1.4" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#are-individual-differences-stable-over-time"><i class="fa fa-check"></i><b>10.1.4</b> Are individual differences stable over time?</a></li>
<li class="chapter" data-level="10.1.5" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#predicting-future-vocabulary-size"><i class="fa fa-check"></i><b>10.1.5</b> Predicting future vocabulary size</a></li>
<li class="chapter" data-level="10.1.6" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#relationships-with-other-child-level-predictors"><i class="fa fa-check"></i><b>10.1.6</b> Relationships with other child-level predictors</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#bayesian-model-results"><i class="fa fa-check"></i><b>10.2</b> Bayesian model results</a><ul>
<li class="chapter" data-level="10.2.1" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#plot-the-intervals-for-the-random-effect-parameters"><i class="fa fa-check"></i><b>10.2.1</b> Plot the intervals for the random effect parameters</a></li>
<li class="chapter" data-level="10.2.2" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#posterior-predictive-checks"><i class="fa fa-check"></i><b>10.2.2</b> Posterior predictive checks</a></li>
<li class="chapter" data-level="10.2.3" data-path="analysis-of-familiar-word-recognition.html"><a href="analysis-of-familiar-word-recognition.html#formal-model-specification"><i class="fa fa-check"></i><b>10.2.3</b> Formal model specification</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="visualize-looks-to-each-image-type.html"><a href="visualize-looks-to-each-image-type.html"><i class="fa fa-check"></i><b>11</b> Visualize looks to each image type</a><ul>
<li class="chapter" data-level="11.1" data-path="visualize-looks-to-each-image-type.html"><a href="visualize-looks-to-each-image-type.html#comparing-strong-versus-weak-foils"><i class="fa fa-check"></i><b>11.1</b> Comparing strong versus weak foils</a></li>
<li class="chapter" data-level="11.2" data-path="visualize-looks-to-each-image-type.html"><a href="visualize-looks-to-each-image-type.html#preparing-data-for-the-model"><i class="fa fa-check"></i><b>11.2</b> Preparing data for the model</a></li>
<li class="chapter" data-level="11.3" data-path="visualize-looks-to-each-image-type.html"><a href="visualize-looks-to-each-image-type.html#looks-to-the-phonological-foil"><i class="fa fa-check"></i><b>11.3</b> Looks to the phonological foil</a></li>
<li class="chapter" data-level="11.4" data-path="visualize-looks-to-each-image-type.html"><a href="visualize-looks-to-each-image-type.html#looks-to-the-semantic-foil"><i class="fa fa-check"></i><b>11.4</b> Looks to the semantic foil</a></li>
<li class="chapter" data-level="11.5" data-path="visualize-looks-to-each-image-type.html"><a href="visualize-looks-to-each-image-type.html#look-for-individual-differences-in-competitor-sensitivity"><i class="fa fa-check"></i><b>11.5</b> Look for individual differences in competitor sensitivity</a></li>
<li class="chapter" data-level="11.6" data-path="visualize-looks-to-each-image-type.html"><a href="visualize-looks-to-each-image-type.html#interim-summary"><i class="fa fa-check"></i><b>11.6</b> Interim summary</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="entropy-in-familiar-word-recognition.html"><a href="entropy-in-familiar-word-recognition.html"><i class="fa fa-check"></i><b>12</b> Entropy in familiar word recognition</a></li>
<li class="part"><span><b>Aim 2: Referent Selection and Mispronunciations</b></span></li>
<li class="chapter" data-level="13" data-path="aim-2-method.html"><a href="aim-2-method.html"><i class="fa fa-check"></i><b>13</b> Aim 2: Method</a><ul>
<li class="chapter" data-level="13.1" data-path="aim-2-method.html"><a href="aim-2-method.html#visual-stimuli"><i class="fa fa-check"></i><b>13.1</b> Visual stimuli</a></li>
<li class="chapter" data-level="13.2" data-path="aim-2-method.html"><a href="aim-2-method.html#coding-notebook"><i class="fa fa-check"></i><b>13.2</b> Coding Notebook</a><ul>
<li class="chapter" data-level="13.2.1" data-path="aim-2-method.html"><a href="aim-2-method.html#data-screening-1"><i class="fa fa-check"></i><b>13.2.1</b> Data screening</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="aim-2-method.html"><a href="aim-2-method.html#prepare-the-dataset-for-modeling-1"><i class="fa fa-check"></i><b>13.3</b> Prepare the dataset for modeling</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="analysis-of-referent-selection.html"><a href="analysis-of-referent-selection.html"><i class="fa fa-check"></i><b>14</b> Analysis of referent selection</a><ul>
<li class="chapter" data-level="14.1" data-path="analysis-of-referent-selection.html"><a href="analysis-of-referent-selection.html#nonwords-versus-real-words"><i class="fa fa-check"></i><b>14.1</b> Nonwords versus real words</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="quick-testing-sandbox.html"><a href="quick-testing-sandbox.html"><i class="fa fa-check"></i><b>15</b> Quick testing sandbox</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="vw-experiment-items.html"><a href="vw-experiment-items.html"><i class="fa fa-check"></i><b>A</b> Items used in the visual world experiment</a></li>
<li class="chapter" data-level="B" data-path="mp-experiment-items.html"><a href="mp-experiment-items.html"><i class="fa fa-check"></i><b>B</b> Items used in the mispronunciation experiment</a></li>
<li class="chapter" data-level="C" data-path="related-work.html"><a href="related-work.html"><i class="fa fa-check"></i><b>C</b> Related Work</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Created with bookdown</a></li>
<li><a href="https://tjmahr.github.io/" target="blank">Tristan Mahr</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">My dissertation</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="visualize-looks-to-each-image-type" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> Visualize looks to each image type</h1>
<p>We continue our exploration of the raw data by aggregating looks to each image type.</p>
<p>Earlier we cleaned the data to remove trials with excessive missing data and blocks of trials with too few trials. Read in that data.</p>
<p>Plot growth curves to each AOI.</p>
<p><img src="15-aim1-notebook_files/figure-html/by-aoi-prop-1.png" width="100%" /></p>
<p>The looks to target increase year over year which decreases the remaining proportion of looks for the other three images each year. To study the relative propensity of looking to each image, we instead can use the log-odds of looking to each AOI versus the unrelated image.</p>
<pre><code>#&gt; Warning: Removed 10559 rows containing non-finite values (stat_smooth).</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/by-aoi-logit-1.png" width="100%" /></p>
<p>Each curve is the log odds of looking to the target, phonological foil, and semantic foil versus the unrelated word. Positive values mean more looks to an image type than the unrelated. If you think of the <em>y</em> axis as the image’s <em>relatedness</em> to the target, you can see a time course of relatedness in each panel: Here early phonological effects meaning early relatedness and later, flatter semantic effects meaning late relatedness. (These effects make even more sense sense if phonological representations affect processing before semantic ones.)</p>
<p>This plot suggests an important finding: Children becoming more sensitive to the phonological and semantic foils as they grow older. (I use the verb <em>suggest</em> because this is still a preliminary, unmodeled finding.) Jan and I had made opposite predictions about whether this would happen. Her argument, I think, was that children become better at word recognition by becoming better able to inhibit interference from competing words. This plot would suggest that they show increased sensitive to the target and foils words by looking less to the unrelated word as they age and reapportioning those looks to the other three lexically relevant words.</p>
<div id="comparing-strong-versus-weak-foils" class="section level2">
<h2><span class="header-section-number">11.1</span> Comparing strong versus weak foils</h2>
<p>In <span class="citation">Law et al. (<a href="#ref-RWLPaper">2016</a>)</span>, we ignored trials for certain items where we didn’t think the phonological or semantic similarity was strong enough. The two sets of phonological foils are shown below.</p>
<table>
<caption><span id="tab:print-phon-foil-tables">Table 11.1: </span>Trials with strong phonological foils.</caption>
<thead>
<tr class="header">
<th align="left">Target</th>
<th align="left">PhonologicalFoil</th>
<th align="left">SemanticFoil</th>
<th align="left">Unrelated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">bear</td>
<td align="left">bell</td>
<td align="left">horse</td>
<td align="left">ring</td>
</tr>
<tr class="even">
<td align="left">bee</td>
<td align="left">bear</td>
<td align="left">fly</td>
<td align="left">heart</td>
</tr>
<tr class="odd">
<td align="left">bell</td>
<td align="left">bee</td>
<td align="left">drum</td>
<td align="left">swing</td>
</tr>
<tr class="even">
<td align="left">dress</td>
<td align="left">drum</td>
<td align="left">shirt</td>
<td align="left">swing</td>
</tr>
<tr class="odd">
<td align="left">drum</td>
<td align="left">dress</td>
<td align="left">bell</td>
<td align="left">sword</td>
</tr>
<tr class="even">
<td align="left">flag</td>
<td align="left">fly</td>
<td align="left">kite</td>
<td align="left">pear</td>
</tr>
<tr class="odd">
<td align="left">fly</td>
<td align="left">flag</td>
<td align="left">bee</td>
<td align="left">pen</td>
</tr>
<tr class="even">
<td align="left">heart</td>
<td align="left">horse</td>
<td align="left">ring</td>
<td align="left">bread</td>
</tr>
<tr class="odd">
<td align="left">heart</td>
<td align="left">horse</td>
<td align="left">ring</td>
<td align="left">pan</td>
</tr>
<tr class="even">
<td align="left">horse</td>
<td align="left">heart</td>
<td align="left">bear</td>
<td align="left">pan</td>
</tr>
<tr class="odd">
<td align="left">pan</td>
<td align="left">pear</td>
<td align="left">spoon</td>
<td align="left">vase</td>
</tr>
<tr class="even">
<td align="left">pan</td>
<td align="left">pear</td>
<td align="left">spoon</td>
<td align="left">bell</td>
</tr>
<tr class="odd">
<td align="left">pear</td>
<td align="left">pen</td>
<td align="left">cheese</td>
<td align="left">ring</td>
</tr>
<tr class="even">
<td align="left">pear</td>
<td align="left">pen</td>
<td align="left">cheese</td>
<td align="left">vase</td>
</tr>
<tr class="odd">
<td align="left">pen</td>
<td align="left">pear</td>
<td align="left">sword</td>
<td align="left">van</td>
</tr>
<tr class="even">
<td align="left">vase</td>
<td align="left">van</td>
<td align="left">gift</td>
<td align="left">swan</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:print-phon-foil-tables">Table 11.1: </span>Trials with weak phonological foils.</caption>
<thead>
<tr class="header">
<th align="left">Target</th>
<th align="left">PhonologicalFoil</th>
<th align="left">SemanticFoil</th>
<th align="left">Unrelated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">bread</td>
<td align="left">bear</td>
<td align="left">cheese</td>
<td align="left">vase</td>
</tr>
<tr class="even">
<td align="left">cheese</td>
<td align="left">shirt</td>
<td align="left">bread</td>
<td align="left">van</td>
</tr>
<tr class="odd">
<td align="left">gift</td>
<td align="left">kite</td>
<td align="left">vase</td>
<td align="left">bread</td>
</tr>
<tr class="even">
<td align="left">kite</td>
<td align="left">gift</td>
<td align="left">flag</td>
<td align="left">shirt</td>
</tr>
<tr class="odd">
<td align="left">ring</td>
<td align="left">swing</td>
<td align="left">dress</td>
<td align="left">flag</td>
</tr>
<tr class="even">
<td align="left">shirt</td>
<td align="left">cheese</td>
<td align="left">dress</td>
<td align="left">fly</td>
</tr>
<tr class="odd">
<td align="left">spoon</td>
<td align="left">swan</td>
<td align="left">pan</td>
<td align="left">drum</td>
</tr>
<tr class="even">
<td align="left">swan</td>
<td align="left">spoon</td>
<td align="left">bee</td>
<td align="left">bell</td>
</tr>
<tr class="odd">
<td align="left">swan</td>
<td align="left">spoon</td>
<td align="left">bee</td>
<td align="left">ring</td>
</tr>
<tr class="even">
<td align="left">swing</td>
<td align="left">spoon</td>
<td align="left">kite</td>
<td align="left">heart</td>
</tr>
<tr class="odd">
<td align="left">sword</td>
<td align="left">swan</td>
<td align="left">pen</td>
<td align="left">gift</td>
</tr>
<tr class="even">
<td align="left">van</td>
<td align="left">pan</td>
<td align="left">horse</td>
<td align="left">sword</td>
</tr>
</tbody>
</table>
<p>The stronger phonological foils are pairs where the syllable onsets are the same. The weaker foils include rime pairs, pairs where the words have different syllable onsets, and pairs where the onsets differ by a phonetic feature.</p>
<table>
<caption><span id="tab:print-semy-foil-tables">Table 11.2: </span>Trials with strong semantic foils.</caption>
<thead>
<tr class="header">
<th align="left">Target</th>
<th align="left">PhonologicalFoil</th>
<th align="left">SemanticFoil</th>
<th align="left">Unrelated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">bear</td>
<td align="left">bell</td>
<td align="left">horse</td>
<td align="left">ring</td>
</tr>
<tr class="even">
<td align="left">bee</td>
<td align="left">bear</td>
<td align="left">fly</td>
<td align="left">heart</td>
</tr>
<tr class="odd">
<td align="left">bell</td>
<td align="left">bee</td>
<td align="left">drum</td>
<td align="left">swing</td>
</tr>
<tr class="even">
<td align="left">bread</td>
<td align="left">bear</td>
<td align="left">cheese</td>
<td align="left">vase</td>
</tr>
<tr class="odd">
<td align="left">cheese</td>
<td align="left">shirt</td>
<td align="left">bread</td>
<td align="left">van</td>
</tr>
<tr class="even">
<td align="left">dress</td>
<td align="left">drum</td>
<td align="left">shirt</td>
<td align="left">swing</td>
</tr>
<tr class="odd">
<td align="left">drum</td>
<td align="left">dress</td>
<td align="left">bell</td>
<td align="left">sword</td>
</tr>
<tr class="even">
<td align="left">fly</td>
<td align="left">flag</td>
<td align="left">bee</td>
<td align="left">pen</td>
</tr>
<tr class="odd">
<td align="left">horse</td>
<td align="left">heart</td>
<td align="left">bear</td>
<td align="left">pan</td>
</tr>
<tr class="even">
<td align="left">pan</td>
<td align="left">pear</td>
<td align="left">spoon</td>
<td align="left">vase</td>
</tr>
<tr class="odd">
<td align="left">pan</td>
<td align="left">pear</td>
<td align="left">spoon</td>
<td align="left">bell</td>
</tr>
<tr class="even">
<td align="left">pear</td>
<td align="left">pen</td>
<td align="left">cheese</td>
<td align="left">ring</td>
</tr>
<tr class="odd">
<td align="left">pear</td>
<td align="left">pen</td>
<td align="left">cheese</td>
<td align="left">vase</td>
</tr>
<tr class="even">
<td align="left">shirt</td>
<td align="left">cheese</td>
<td align="left">dress</td>
<td align="left">fly</td>
</tr>
<tr class="odd">
<td align="left">spoon</td>
<td align="left">swan</td>
<td align="left">pan</td>
<td align="left">drum</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:print-semy-foil-tables">Table 11.2: </span>Trials with weak semantic foils.</caption>
<thead>
<tr class="header">
<th align="left">Target</th>
<th align="left">PhonologicalFoil</th>
<th align="left">SemanticFoil</th>
<th align="left">Unrelated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">flag</td>
<td align="left">fly</td>
<td align="left">kite</td>
<td align="left">pear</td>
</tr>
<tr class="even">
<td align="left">gift</td>
<td align="left">kite</td>
<td align="left">vase</td>
<td align="left">bread</td>
</tr>
<tr class="odd">
<td align="left">heart</td>
<td align="left">horse</td>
<td align="left">ring</td>
<td align="left">bread</td>
</tr>
<tr class="even">
<td align="left">heart</td>
<td align="left">horse</td>
<td align="left">ring</td>
<td align="left">pan</td>
</tr>
<tr class="odd">
<td align="left">kite</td>
<td align="left">gift</td>
<td align="left">flag</td>
<td align="left">shirt</td>
</tr>
<tr class="even">
<td align="left">pen</td>
<td align="left">pear</td>
<td align="left">sword</td>
<td align="left">van</td>
</tr>
<tr class="odd">
<td align="left">ring</td>
<td align="left">swing</td>
<td align="left">dress</td>
<td align="left">flag</td>
</tr>
<tr class="even">
<td align="left">swan</td>
<td align="left">spoon</td>
<td align="left">bee</td>
<td align="left">bell</td>
</tr>
<tr class="odd">
<td align="left">swan</td>
<td align="left">spoon</td>
<td align="left">bee</td>
<td align="left">ring</td>
</tr>
<tr class="even">
<td align="left">swing</td>
<td align="left">spoon</td>
<td align="left">kite</td>
<td align="left">heart</td>
</tr>
<tr class="odd">
<td align="left">sword</td>
<td align="left">swan</td>
<td align="left">pen</td>
<td align="left">gift</td>
</tr>
<tr class="even">
<td align="left">van</td>
<td align="left">pan</td>
<td align="left">horse</td>
<td align="left">sword</td>
</tr>
<tr class="odd">
<td align="left">vase</td>
<td align="left">van</td>
<td align="left">gift</td>
<td align="left">swan</td>
</tr>
</tbody>
</table>
<p>The strong semantic foils belong to the same category and the weaker ones have a less obvious relationship (<em>ring</em> and <em>dress</em>).</p>
<p>We visually confirm that the strong versus weak foils behave differently.</p>
<pre><code>#&gt; Warning: Removed 48304 rows containing non-finite values (stat_smooth).</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/by-aoi-logit-foils-1.png" width="100%" /></p>
<pre><code>#&gt; Warning: Removed 43071 rows containing non-finite values (stat_smooth).</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/by-aoi-logit-foils-2.png" width="100%" /></p>
<p>What’s going on here:</p>
<ul>
<li>The weak phonological foils are indeed weaker than the strong foils.</li>
<li>The strong semantic foils appear stronger than the weak ones. The strong foils show a growth curve pattern of increasing looks away from baseline and there a developmental difference among the growth curves for each time point.</li>
<li>Children have a lower advantage for the target (vs unrelated) in weak foil trials because… why? My reading is that if the semantic or phonological foil is effective, children will look at it instead of the unrelated image. Conversely, if the semantic or phonological foil are less effective, children will look more to the unrelated image, which pulls down the ratio of looks to target versus the unrelated image.</li>
</ul>
<p>In the above plots, we fixed the denominator to be the number of looks to the unrelated image and varied the numerator. In the plots below, we fix the numerator to be the looks to the target and vary the denominator to looks to target versus looks to each foil.</p>
<pre><code>#&gt; Warning: Removed 37498 rows containing non-finite values (stat_smooth).</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/by-aoi-logit-target-phon-1.png" width="100%" /></p>
<p>Curves in both panels attain the same height, so phonological and unrelated foils affect processing equally later in the trial. The strong phonological foils curves in the Target vs Phonological comparison rise later than the weak foils, reflecting early looks to the phonological foils.</p>
<pre><code>#&gt; Warning: Removed 29775 rows containing non-finite values (stat_smooth).</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/by-aoi-logit-target-semi-1.png" width="100%" /></p>
<p>Curves in the two panels do not attain the same height, so the semantic foil reduces odds of fixating to the target later on in a trial. There appears to be no difference in strong and weak foils in Year 2 and Year 3, so I might be able to collapse to remove this distinction and include more items in the analysis.</p>
</div>
<div id="preparing-data-for-the-model" class="section level2">
<h2><span class="header-section-number">11.2</span> Preparing data for the model</h2>
<pre><code>#&gt; Modelling options:
#&gt; List of 4
#&gt;  $ bin_width : num 3
#&gt;  $ start_time: num 250
#&gt;  $ end_time  : num 1500
#&gt;  $ bin_length: num 50
#&gt; </code></pre>
</div>
<div id="looks-to-the-phonological-foil" class="section level2">
<h2><span class="header-section-number">11.3</span> Looks to the phonological foil</h2>
<p>Next, we asked how children’s sensitivity to the phonological foils changed over developmental time. We only examined trials for which the phonological foil and the noun shared the same syllable onset. For example, this criterion included trials with <em>dress</em>–<em>drum</em>, <em>fly</em>–<em>flag</em>, or <em>horse</em>–<em>heart</em>, but it excluded trials <em>kite</em>–<em>gift</em> (feature difference), <em>bear</em>–<em>bread</em> (onset difference), and <em>ring</em>–<em>swing</em> (rimes). We kept 13 of the 24 trials.</p>
<p>The outcome measure for these analyses was the log-odds of fixating on the phonological foil versus the unrelated image. Because children looked more to the target word with each year of the study, they necessarily looked less to the distractors each year. Figure N below illustrates how the proportions of looks to the phonological foils declined each year. Therefore, we examined the effect of the phonological foil in comparison to the unrelated foil. For example, on the trials where the target is <em>fly</em>, we study the effect of the phonological foil <em>flag</em> by looking at when and to what to degree the children fixate on <em>flag</em> more than the unrelated image <em>pen</em>. If a window of time of shows a consistent advantage for the phonological foil over the unrelated image, we can conclude that the children were sensitive to the phonological foil. By studying the time course of fixations to the phonological foil versus the unrelated image, we can identify when the phonological foil affected word recognition most significantly.</p>
<p>As in the previous models, we downsampled the data into 50-ms (3-frame) bins in order to smooth the data. We modeled the looks from 250 to 1500 ms. Lastly, we aggregated looks by child, study and time.</p>
<p><img src="15-aim1-notebook_files/figure-html/declining-phon-props-1.png" width="80%" /></p>
<p>To account for the sparseness of the data, we used the empirical log-odds (or empirical logit) transformation <span class="citation">(Barr, <a href="#ref-Barr2008">2008</a>)</span>. This transformation adds .5 to the looking counts. For example, a time-frame with 4 looks to the phonological foil and 1 look to the unrelated image has a conventional log-odds of log(4/1) = 1.39 and empirical log-odds of log(4.5/1.5) = 1.10. This transformation fills in 0 values, and it dampens the extremeness of some probabilities that arise in sparse count data.</p>
<p>We fit a generalized additive model with fast restricted maximum likelihood estimation <span class="citation">(Sóskuthy, <a href="#ref-Soskuthy2017">2017</a> for a tutorial for linguists; Wood, <a href="#ref-Wood2017">2017</a>)</span>. Box 1 provides a brief overview of these models. We fit the models using the R package <code>mgcv</code> <span class="citation">(vers. 1.8.23; Wood, <a href="#ref-Wood2017">2017</a>)</span> with support from the tools in the <code>itsadug</code> package <span class="citation">(vers. 2.3; van Rij, Wieling, Baayen, &amp; van Rijn, <a href="#ref-itsadug">2017</a>)</span>.</p>
<div class="infobox">
<p><strong>Box 1: The Intuition Behind Generalized Additive Models</strong>.</p>
<p>In these analyses, the outcome of interest is a value that changes over time in a nonlinear way. We model these time series by building a set of features to represent time values. In the growth curve analyses of familiar word recognition, we used a set of polynomial features which expressed time as the weighted sum of a linear trend, a quadratic trend and cubic trend. That is:</p>
<p><span class="math display">\[
\text{log-odds}(\mathit{looking}) = 
  \alpha + \beta_1 * \textit{Time}^1 +
           \beta_2 * \textit{Time}^2 +
           \beta_3 * \textit{Time}^3
\]</span></p>
<p>But another way to think about the polynomial terms is as <em>basis functions</em>: A set of features that combine to approximate some nonlinear function of time. Under this framework, the model can be expressed as:</p>
<p><span class="math display">\[
\text{log-odds}(\mathit{looking}) = 
  \alpha + f(\textit{Time})
\]</span></p>
<p>This is the idea behind generalized additive models and their <em>smooth terms</em>. These smooths fit nonlinear functions of data by weighting and adding simple functions together. The figures below show 9 basis functions from a “thin-plate spline” and how they can be weighted and summed to fit a growth curve.</p>
<p><img src="15-aim1-notebook_files/figure-html/infobox-1-figs-1.png" width="66%" /></p>
<p>Each of these basis functions is weighted by a model coefficient, but the individual basis functions are not a priori meaningful. Rather, it is the whole set of functions that approximate the curvature of the data—i.e., <em>f</em>(Time))—so we statistically evaluate the whole batch of coefficients simultaneously. This joint testing is similar to how one might test a batch of effects in an ANOVA. If the batch of effects jointly improve model fit, we infer that there is a significant smooth or shape effect. (Not quite sure this is 100% accurate yet.)</p>
<p>Smooth terms come with an estimated degrees of freedom (EDF). These values provide a sense of how many degrees of freedom the smooth consumed. An EDF of 1 is a perfectly straight line, indicating no smoothing. Higher EDF values indicate that the smooth term captured more curvature from the data.</p>
<!-- The other important thing to know about generalized additive models is that -->
<!-- wigglyness is penalized. With so many functions, one might worry about -->
<!-- overfitting the data and including incidental wiggliness into *f*(Time). These -->
<!-- models, however, include a smoothing parameter that -->
</div>
<p>The model included main effects of study year. These <em>parametric</em> terms work like conventional regression effects and determined the growth curve’s average values. We used age 4 as the reference year, so the model’s intercept represented the average looking probability at age 4. The model’s year effects therefore represented differences between age 4 vs. age 3 and age 4 vs. age 5.</p>
<p>The model also included <em>smooth</em> terms to represent the time course of the data. We included a smooth term for trial time to represent a general effect of time following noun onset across all studies, and we also included smooth terms for time for each study. These study-specific smooths estimate how the shape of the data differs in each individual study. Each of these smooths used 10 knots (9 basis functions). We also included child-level “random smooths” to represent child-level variation in growth curve shapes. Because we have much as less data at the child level than at the study level, these random smooths only included 5 knots (4 basis functions). We can think of these simpler splines as coarse adjustments in growth curve shape to capture child-level variation from limited data. Altogether, the model contained the following terms:</p>
<pre><code>emp. log-odds(phonological vs. unrelated) = 
  α + β1*Study1 + β2*Study3 +   [growth curve averages]
  f1(Time) +                    [general smooth]
  f2(Time, Age-3) +             [study-specific smooths]
  f3(Time, Age-4) + 
  f4(Time, Age-5) + 
  f5(Time, Child-ID)            [by-child random smooths]</code></pre>
<p>The model’s fitted values are shown in Figure N. These are the average empirical log-odds of fixating on the phonological foil versus the unrelated image for each year of the study. The model captured the trend for increased looks to the competitor image with each year of the study. At age 4 and age 5, the shape rises from a baseline to the peak around 800 ms. These curves slope downwards and eventually fall beneath the initial baseline. The shape at age 3 does not have a steady rise from baseline and shows a very small peak around 800 ms.</p>
<p><img src="15-aim1-notebook_files/figure-html/phon-vs-unre-fits-1.png" width="80%" /></p>
<p>The average looks to the phonological foil over the unrelated for age 4 was 0.17 emp. log-odds, .54 proportion units. The averages for age 3 and age 4 did not significantly differ, <em>p</em> = .43 but the average value was significantly greater at age 5, 0.33 emp. log-odds, .58 proportion units, <em>p</em> .43. Visually, this effect shows up in the almost constant height difference between the age-4 and the age-5 curves.</p>
<p>There was a significant smooth term for time in general, estimated degrees of freedom (EDF) = 6.78, <em>p</em> &lt; .001, and for the age-3 smooth, EDF = 4.39, <em>p</em> &lt; .001. In contrast, the age-4 and age-5 smooths did not differ significantly from the general time smooth, age-4 EDF = 1.00, age-4 <em>p</em> = .195, age-5 EDF = 1.00, age-5 <em>p</em> = .394. The shapes of the age-4 and age-5 growth curves showed the same general shape but with different heights.</p>
<p>We also computed the difference between the growth curves from successive studies. These are shown in Figure N. The curves of the age-3 and age-4 were significantly different from 500 to 1050 ms. This result confirms that the looks to the phonological foil increased from age 3 and age 4 during the time window immediately following presentation of the noun. The similarity between the phonological foil and the target occurs early in the trial. Given the 150–300 ms time required to execute an eye movement in response to speech, the time window for these differences indicates that children became more sensitive to the phonological similarities between the foil and the target from age 3 to age 4.</p>
<p>The two curves also differed significantly after 1250 ms. The effect reflects how the looks to phonological foil decreased as the trial progresses. After an incorrect look to the foil, the children on average corrected their gaze and looked even less to the phonological foil. We do not observe this degree of correction during age 3 presumably because children hardly looked to the phonological foil early on.</p>
<p><img src="15-aim1-notebook_files/figure-html/phon-diff-curves-1.png" width="80%" /></p>
<p>In contrast, the difference between the age-4 and age-5 smooths is driven primarily by the intercept difference and a linear diverging trend—that is, the distance between the two grows slightly over time. The same general curvature was observed for the two studies, reflecting the same general looking behavior at both time points. Children showed an early increase in looks to the phonological foil relative to the unrelated image but after receiving disqualifying information from the rest of the word, the looks to the phonological foil rapidly decrease. The primary difference between age-4 and age-5 is that the foil effect was more pronounced at age 5.</p>
<p>Talking points:</p>
<ul>
<li>Children increased their relative looks to the phonological foil with each year of the study. Although they looked to the target more quickly and more reliably with each of the study, the advantage of the phonological foil over the unrelated image increased with each year. Thus, the children became more sensitive to the phonological cohort words as they grew older.</li>
<li>There is hardly an effect of the phonological foil during timepoint 1. There are a few ways to interpret this finding. The first may be artefactual. The stimuli were re-recorded at timepoint 2 so the timepoint 1 stimuli were somewhat longer on average (around 800 ms at TP1 vs. 550–800ms later on). However, with slower stimuli, we would still expect an inflection in looks to the foil as children have more time to activate the phonological representations to the cohort. In other words, with more time to respond, there could plausibly be an even greater effect of early phonological information.</li>
<li>Alternatively, the children in timepoint 1 may not be using the early similarity of words during word recognition. That is, instead of immediate incremental activation of lexical cohorts, the children may not be activating the cohorts as reliably. This would imply that further study is required on the evidence for when young children begin to show immediate activation of cohorts.</li>
<li>The children at timepoint1 may not be incrementally activating the cohorts. The children in timepoint 2 and 3 certainly are.</li>
<li>Incremental activation and early commitments to partial information goes up with age.</li>
</ul>
<p>Here we have the data and the model fits.</p>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-9-1.png" width="80%" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">itsadug<span class="op">::</span><span class="kw">gamtabs</span>(b2r, <span class="dt">type =</span> <span class="st">&quot;html&quot;</span>)</code></pre></div>
<!-- html table generated in R 3.4.3 by xtable 1.8-2 package -->
<!-- Sat Mar 03 11:53:26 2018 -->
<table border="1">
<caption align="bottom">
</caption>
<tr>
<td>
A. parametric coefficients
</td>
<td align="right">
Estimate
</td>
<td align="right">
Std. Error
</td>
<td align="right">
t-value
</td>
<td align="right">
p-value
</td>
</tr>
<tr>
<td>
(Intercept)
</td>
<td align="right">
0.1661
</td>
<td align="right">
0.0491
</td>
<td align="right">
3.3857
</td>
<td align="right">
0.0007
</td>
</tr>
<tr>
<td>
STimePoint1
</td>
<td align="right">
-0.0123
</td>
<td align="right">
0.0156
</td>
<td align="right">
-0.7931
</td>
<td align="right">
0.4277
</td>
</tr>
<tr>
<td>
STimePoint3
</td>
<td align="right">
0.1612
</td>
<td align="right">
0.0153
</td>
<td align="right">
10.5327
</td>
<td align="right">
&lt; 0.0001
</td>
</tr>
<tr>
<td>
B. smooth terms
</td>
<td align="right">
edf
</td>
<td align="right">
Ref.df
</td>
<td align="right">
F-value
</td>
<td align="right">
p-value
</td>
</tr>
<tr>
<td>
s(Time)
</td>
<td align="right">
6.7768
</td>
<td align="right">
7.7740
</td>
<td align="right">
8.5686
</td>
<td align="right">
&lt; 0.0001
</td>
</tr>
<tr>
<td>
s(Time):STimePoint2
</td>
<td align="right">
1.0003
</td>
<td align="right">
1.0005
</td>
<td align="right">
1.6769
</td>
<td align="right">
0.1954
</td>
</tr>
<tr>
<td>
s(Time):STimePoint1
</td>
<td align="right">
4.3905
</td>
<td align="right">
5.4940
</td>
<td align="right">
13.1740
</td>
<td align="right">
&lt; 0.0001
</td>
</tr>
<tr>
<td>
s(Time):STimePoint3
</td>
<td align="right">
1.0004
</td>
<td align="right">
1.0007
</td>
<td align="right">
0.7255
</td>
<td align="right">
0.3943
</td>
</tr>
<tr>
<td>
s(Time,R)
</td>
<td align="right">
832.5109
</td>
<td align="right">
974.0000
</td>
<td align="right">
11.5381
</td>
<td align="right">
&lt; 0.0001
</td>
</tr>
<a name=tab.gam></a>
</table>
</div>
<div id="looks-to-the-semantic-foil" class="section level2">
<h2><span class="header-section-number">11.4</span> Looks to the semantic foil</h2>
<p>We used a similiar procedure on the looks to the semantic foil.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n_semy &lt;-<span class="st"> </span>semy_foils<span class="op">$</span>strong_foil<span class="op">$</span>Target <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unique</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">length</span>()</code></pre></div>
<p>Next, we asked how children’s sensitivity to the semantic foils changed over developmental time. We only examined trials for which the semantic foil and the noun were part of the same category. We kept trials, for example, with <em>bee</em>–<em>fly</em>, <em>shirt</em>–<em>dress</em>, or <em>spoon</em>–<em>pan</em>, but we excluded trials where the similarity was perceptual (<em>sword</em>–<em>pen</em>) or too abstract (<em>swan</em>–<em>bee</em>). We kept 13 of the 24 trials.</p>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-12-1.png" width="80%" /></p>
<pre><code>#&gt; 
#&gt; Family: gaussian 
#&gt; Link function: identity 
#&gt; 
#&gt; Formula:
#&gt; elog ~ S + s(Time) + s(Time, by = S)
#&gt; 
#&gt; Parametric coefficients:
#&gt;             Estimate Std. Error t value Pr(&gt;|t|)    
#&gt; (Intercept)  0.43802    0.01097  39.919  &lt; 2e-16 ***
#&gt; STimePoint1 -0.12954    0.01557  -8.322  &lt; 2e-16 ***
#&gt; STimePoint3  0.07938    0.01574   5.043  4.6e-07 ***
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
#&gt; 
#&gt; Approximate significance of smooth terms:
#&gt;                       edf Ref.df      F  p-value    
#&gt; s(Time)             6.792  7.879 27.318  &lt; 2e-16 ***
#&gt; s(Time):STimePoint2 1.078  1.142  0.605 0.422443    
#&gt; s(Time):STimePoint1 1.143  1.261  0.286 0.705947    
#&gt; s(Time):STimePoint3 2.699  3.567  6.321 0.000141 ***
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
#&gt; 
#&gt; Rank: 38/39
#&gt; R-sq.(adj) =  0.0711   Deviance explained = 7.15%
#&gt; -REML =  47702  Scale est. = 1.2714    n = 30976</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-12-2.png" width="80%" /></p>
<pre><code>#&gt;            df      AIC
#&gt; s2n  9.165313 95563.23
#&gt; s2  16.898148 95363.53</code></pre>
<p>The model’s predictions are shown in the figure. It captured the trend for increased looks to the competitor image with each year of the study.</p>
<pre><code>#&gt; Summary:
#&gt;  * S : factor; set to the value(s): TimePoint1, TimePoint2, TimePoint3. 
#&gt;  * Time : numeric predictor; with 30 values ranging from 250.000000 to 1800.000000.</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-13-1.png" width="80%" /></p>
<p>We also computed the difference of the curves from different studies. The difference from timepoint 1 to timepoint 2 is just a matter of height.</p>
<pre><code>#&gt; Summary:
#&gt;  * Time : numeric predictor; with 100 values ranging from 250.000000 to 1800.000000.</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-14-1.png" width="80%" /></p>
<pre><code>#&gt; 
#&gt; Time window(s) of significant difference(s):
#&gt;  250.000000 - 1800.000000</code></pre>
<p>The difference from timepoint 2 to timepoint 3 includes a slight bump as the two curves diverge from a similar starting position.</p>
<pre><code>#&gt; Summary:
#&gt;  * Time : numeric predictor; with 100 values ranging from 250.000000 to 1800.000000.</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-15-1.png" width="80%" /></p>
<pre><code>#&gt; 
#&gt; Time window(s) of significant difference(s):
#&gt;  735.353535 - 1596.464646</code></pre>
<p>Timepoint 3 and timepoint 1 differ too.</p>
<pre><code>#&gt; Summary:
#&gt;  * Time : numeric predictor; with 100 values ranging from 250.000000 to 1800.000000.</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-16-1.png" width="80%" /></p>
<pre><code>#&gt; 
#&gt; Time window(s) of significant difference(s):
#&gt;  312.626263 - 1800.000000</code></pre>
<p>Here we have the data and the model fits.</p>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-17-1.png" width="80%" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">itsadug<span class="op">::</span><span class="kw">gamtabs</span>(s2, <span class="dt">type =</span> <span class="st">&quot;html&quot;</span>)</code></pre></div>
<!-- html table generated in R 3.4.3 by xtable 1.8-2 package -->
<!-- Sat Mar 03 11:53:44 2018 -->
<table border="1">
<caption align="bottom">
</caption>
<tr>
<td>
A. parametric coefficients
</td>
<td align="right">
Estimate
</td>
<td align="right">
Std. Error
</td>
<td align="right">
t-value
</td>
<td align="right">
p-value
</td>
</tr>
<tr>
<td>
(Intercept)
</td>
<td align="right">
0.4380
</td>
<td align="right">
0.0110
</td>
<td align="right">
39.9190
</td>
<td align="right">
&lt; 0.0001
</td>
</tr>
<tr>
<td>
STimePoint1
</td>
<td align="right">
-0.1295
</td>
<td align="right">
0.0156
</td>
<td align="right">
-8.3225
</td>
<td align="right">
&lt; 0.0001
</td>
</tr>
<tr>
<td>
STimePoint3
</td>
<td align="right">
0.0794
</td>
<td align="right">
0.0157
</td>
<td align="right">
5.0433
</td>
<td align="right">
&lt; 0.0001
</td>
</tr>
<tr>
<td>
B. smooth terms
</td>
<td align="right">
edf
</td>
<td align="right">
Ref.df
</td>
<td align="right">
F-value
</td>
<td align="right">
p-value
</td>
</tr>
<tr>
<td>
s(Time)
</td>
<td align="right">
6.7920
</td>
<td align="right">
7.8788
</td>
<td align="right">
27.3184
</td>
<td align="right">
&lt; 0.0001
</td>
</tr>
<tr>
<td>
s(Time):STimePoint2
</td>
<td align="right">
1.0776
</td>
<td align="right">
1.1421
</td>
<td align="right">
0.6050
</td>
<td align="right">
0.4224
</td>
</tr>
<tr>
<td>
s(Time):STimePoint1
</td>
<td align="right">
1.1427
</td>
<td align="right">
1.2614
</td>
<td align="right">
0.2861
</td>
<td align="right">
0.7059
</td>
</tr>
<tr>
<td>
s(Time):STimePoint3
</td>
<td align="right">
2.6995
</td>
<td align="right">
3.5673
</td>
<td align="right">
6.3211
</td>
<td align="right">
0.0001
</td>
</tr>
<a name=tab.gam></a>
</table>
</div>
<div id="look-for-individual-differences-in-competitor-sensitivity" class="section level2">
<h2><span class="header-section-number">11.5</span> Look for individual differences in competitor sensitivity</h2>
<p>[…put this on hold for a while…]</p>
<!-- Let's just run with all the foils. There's a trade-off here about sparsity and -->
<!-- strength of the stimuli. -->
<pre><code>#&gt; Parsed with column specification:
#&gt; cols(
#&gt;   .default = col_integer(),
#&gt;   Study = col_character(),
#&gt;   ResearchID = col_character(),
#&gt;   Female = col_logical(),
#&gt;   Male = col_logical(),
#&gt;   MAE = col_logical(),
#&gt;   AAE = col_logical(),
#&gt;   Maternal_Education_LMH = col_character(),
#&gt;   MinPair_ProportionCorrect = col_double(),
#&gt;   SAILS_ProportionTestCorrect = col_double()
#&gt; )
#&gt; See spec(...) for full column specifications.
#&gt; Joining, by = &quot;ResearchID&quot;
#&gt; `geom_smooth()` using method = &#39;gam&#39;</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-19-1.png" width="100%" /></p>
<pre><code>#&gt; Joining, by = &quot;ResearchID&quot;
#&gt; `geom_smooth()` using method = &#39;gam&#39;</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-19-2.png" width="100%" /></p>
<pre><code>#&gt; Parsed with column specification:
#&gt; cols(
#&gt;   .default = col_integer(),
#&gt;   Study = col_character(),
#&gt;   ResearchID = col_character(),
#&gt;   Female = col_logical(),
#&gt;   Male = col_logical(),
#&gt;   MAE = col_logical(),
#&gt;   AAE = col_logical(),
#&gt;   Maternal_Education_LMH = col_character(),
#&gt;   MinPair_ProportionCorrect = col_double(),
#&gt;   SAILS_ProportionTestCorrect = col_double()
#&gt; )
#&gt; See spec(...) for full column specifications.
#&gt; Joining, by = &quot;ResearchID&quot;
#&gt; `geom_smooth()` using method = &#39;gam&#39;</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-19-3.png" width="100%" /></p>
<pre><code>#&gt; Joining, by = &quot;ResearchID&quot;
#&gt; `geom_smooth()` using method = &#39;gam&#39;</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-19-4.png" width="100%" /></p>
<pre><code>#&gt; Joining, by = &quot;ResearchID&quot;
#&gt; `geom_smooth()` using method = &#39;gam&#39;</code></pre>
<p><img src="15-aim1-notebook_files/figure-html/unnamed-chunk-19-5.png" width="100%" /></p>
</div>
<div id="interim-summary" class="section level2">
<h2><span class="header-section-number">11.6</span> Interim summary</h2>
<ul>
<li>Visual evidence that the semantic foil and phonological foil become more relevant (compared to unrelated foil) each year.</li>
<li>Our previous distinction between strong and weak foils still applies, although it might be better to exclude only the (a priori) weakest foils, like the rime phonological foils.</li>
</ul>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-RWLPaper">
<p>Law, F., II, Mahr, T., Schneeberg, A., &amp; Edwards, J. R. (2016). Vocabulary size and auditory word recognition in preschool children. <em>Applied Psycholinguistics</em>. doi:<a href="https://doi.org/10.1017/S0142716416000126">10.1017/S0142716416000126</a></p>
</div>
<div id="ref-Barr2008">
<p>Barr, D. J. (2008). Analyzing ‘visual world’ eyetracking data using multilevel logistic regression. <em>Journal of Memory and Language</em>, <em>59</em>(4), 457–474. doi:<a href="https://doi.org/10.1016/j.jml.2007.09.002">10.1016/j.jml.2007.09.002</a></p>
</div>
<div id="ref-Soskuthy2017">
<p>Sóskuthy, M. (2017). Generalised additive mixed models for dynamic analysis in linguistics: a practical introduction. Retrieved from <a href="http://arxiv.org/abs/1703.05339" class="uri">http://arxiv.org/abs/1703.05339</a></p>
</div>
<div id="ref-Wood2017">
<p>Wood, S. N. (2017). <em>Generalized additive models: An introduction with R</em> (2nd ed.). CRC Press.</p>
</div>
<div id="ref-itsadug">
<p>van Rij, J., Wieling, M., Baayen, R. H., &amp; van Rijn, H. (2017). itsadug: Interpreting time series and autocorrelated data using gamms.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analysis-of-familiar-word-recognition.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="entropy-in-familiar-word-recognition.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["dissertation.pdf", "dissertation.epub", "dissertation.docx"],
"toc": {
"collapse": "subsection"
},
"split_bib": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
